---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: localhost
  user: root
  tasks:

    - name: Configure Gluster volume.
      gluster_volume:
        state: present
        name: "datastore"
        bricks: "/brick/brick1,/brick/brick2"
        replicas: 2
        cluster: "{{ ansible_hostname }}"
        host: "{{ ansible_hostname }}"
        force: yes

    - name: Start Gluster volume
      gluster_volume: name=datastore state=started

    - name: generate ssh final key
      user: name=root generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
      when: master == true

    - name: add authorized key
      shell: |
              cat /root/.ssh/id_rsa.pub | ssh -oPasswordAuthentication=no -oStrictHostKeyChecking=no root@{{ hostname_slave }} -i /root/.ssh/init.pem "cat > /root/.ssh/authorized_keys"
               > /root/.ssh/authorized_keys
      when: master == true

    - name: purge keys
      shell: |
              rm -rf /root/.ssh/init.pem
              rm -rf /root/.ssh/init.pem.pub


    - name: geo replication
      shell: |
               gluster system:: execute gsec_create
               gluster vol geo-rep datastore {{ hostname_slave }}::datastore create push-pem force
               gluster vol geo-rep datastore {{ hostname_slave }}::datastore start
      when: master == true
